name: Deno Deploy
on:
  workflow_run:
    workflows: ["Bump Tag"]
    types:
      - completed
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: get latest tag
        id: latest_tag
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags --abbrev=0)
          echo "::set-output name=tag::$latest_tag"
      - name: setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: build npm package
        run: |
          deno run -A ./build.ts ${{ steps.latest_tag.outputs.tag }}
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
      - name: publish to npm
        run: |
          cd npm
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
